apiVersion: v1
kind: Service
metadata:
  name: llm-gateway-service
spec:
  selector:
    app: llm-platform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
